#!/usr/bin/env php
<?php

$pkg = json_decode(file_get_contents(__DIR__ . '/composer.json'));

function recursive_copy($source, $destination) {
    $op = [$source, $destination];

    if (is_link($source)) {
        symlink(readlink($source), $destination);

        return [];
    }

    if (is_dir($source)) {
        $results = [$op];

        if (is_dir($destination) === false) {
            mkdir($destination);
        }

        foreach (scandir($source) as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }

            $subResults = recursive_copy(
                $source . DIRECTORY_SEPARATOR . $file,
                $destination . DIRECTORY_SEPARATOR . $file
            );

            if (count($subResults) === 2 && is_string($subResults[0])) {
                $results[] = $subResults;
            } else {
                $results = array_merge($results, $subResults);
            }

        }

        return $results;
    }

    if (is_file($source)) {
        copy(...$op);

        return $op;
    }

    return [null, sprintf('Warning: Cannot copy “%s” (unknown file type).', $source)];
}

printf("\e[35m

    ╔═══════════════════════════╗
    ║                           ║
    ║    \e[97mµ framework \e[90m(v%s)\e[35m   ║
    ║                           ║
    ╚═══════════════════════════╝\e[0m


    Do you want to bootstrap a blank \e[35mµ\e[0m project? [Y/n] ", $pkg->version);


if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    $go = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
    $go = readline();
}

if ($go && strtolower($go) !== 'Y') {
    printf("
    Okay, cool. 👋
");

    return;
}

printf("\e[90m

    %s\e[0m
    
    Done. 👍
",
    implode(
        "\n    ",
        array_map(
            function($item) {
                return sprintf(
                    "%s \e[97m→\e[90m %s",
                    $item[0],
                    str_replace(getcwd(), '.', $item[1])
                );
            },
            recursive_copy(
                join(DIRECTORY_SEPARATOR, [__DIR__, 'boilerplates', 'blank']),
                getcwd()
            )
        )
    )
);
