paths:
  assets: ./
  public:
  views: ../views
#db:
#  database_type: sqlite
#  database_file: ../store/database.db
#router:
#  cache: true
#  cacheFile: ../cache/router.cache
#error:
#  formatter: json
