# All settings that are used internally by micro
# go under the µ key.
µ:
  # Settings (mostly) used by Plates.
  paths:

    # Physical path to your assets. Use this if you want
    # to use the asset extension for cache busting files.
    #
    # @see http://platesphp.com/v3/extensions/asset/
    assets: ./

    # Not used by Plates, but useful for handling different environments.
    public: ''

    # Path to templates.
    views: ../views


  # Database settings for Medoo.
  #
  # @see https://medoo.in/doc
  # db:
    # database_type: sqlite
    # database_file: ../store/database.db

    # database_type: mysql
    # database_name: name
    # server: localhost
    # username: your_username
    # password: your_password

    # charset: utf8
    # port: 3306
    # prefix: myprefix_

    # Enable logging (Logging is disabled by default for better performance)
    # logging: true

    # MySQL socket (shouldn't be used with server and port)
    # socket: /tmp/mysql.sock

    # Driver options for the connection.
    #
    # @see http://www.php.net/manual/en/pdo.setattribute.php
    # option:
    #   !php/const PDO::ATTR_ERRMODE: !php/const PDO::ERRMODE_EXCEPTION

    # Medoo will execute those commands after connecting to the database for initialization.
    # command:
    #   - SET SQL_MODE=ANSI_QUOTES


  # Settings for FastRoute.
  # router:
    # cache: true
    # cacheFile: ../cache/router.cache


  # Settings for BooBoo.
  # error:
    # formatter: json


